### ISSUE TITLE
1.14.2 error

### ISSUE THREAD

**Issue by mctool** [lishid/OpenInv#104]
[18:30:04] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to OpenInv v4.0.1
java.lang.NoSuchMethodError: net.minecraft.server.v1_14_R1.TileEntityShulkerBox.t()Lnet/minecraft/server/v1_14_R1/TileEntityShulkerBox$AnimationPhase;
	at com.lishid.openinv.internal.v1_14_R1.AnySilentContainer.isBlockedShulkerBox(AnySilentContainer.java:140) ~[?:?]
	at com.lishid.openinv.internal.v1_14_R1.AnySilentContainer.isAnyContainerNeeded(AnySilentContainer.java:93) ~[?:?]
	at com.lishid.openinv.listeners.PlayerListener.onPlayerInteract(PlayerListener.java:65) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor106.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[Paper-1.14.2-b51.jar:git-Paper-51]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[Paper-1.14.2-b51.jar:git-Paper-51]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Paper-1.14.2-b51.jar:git-Paper-51]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:534) ~[Paper-1.14.2-b51.jar:git-Paper-51]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:445) ~[Paper-1.14.2-b51.jar:git-Paper-51]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:441) ~[Paper-1.14.2-b51.jar:git-Paper-51]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1391) ~[Paper-1.14.2-b51.jar:git-Paper-51]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[Paper-1.14.2-b51.jar:git-Paper-51]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[Paper-1.14.2-b51.jar:git-Paper-51]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[Paper-1.14.2-b51.jar:git-Paper-51]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[Paper-1.14.2-b51.jar:git-Paper-51]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[Paper-1.14.2-b51.jar:git-Paper-51]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[Paper-1.14.2-b51.jar:git-Paper-51]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[Paper-1.14.2-b51.jar:git-Paper-51]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:998) ~[Paper-1.14.2-b51.jar:git-Paper-51]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:991) ~[Paper-1.14.2-b51.jar:git-Paper-51]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[Paper-1.14.2-b51.jar:git-Paper-51]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:975) ~[Paper-1.14.2-b51.jar:git-Paper-51]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[Paper-1.14.2-b51.jar:git-Paper-51]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]

**Comment by Jikoo** [comment]
Please update to 4.0.3.
