### ISSUE TITLE
1.14.3 error

### ISSUE THREAD

**Issue by mikroskeem** [lishid/OpenInv#108]
Every once in a while server gets this error:

Running Paper git-Paper-134 and OpenInv 4.0.4

```
[19:42:14 ERROR]: Could not pass event PlayerInteractEvent to OpenInv v4.0.4
java.lang.IllegalArgumentException: Cannot get property BlockStateEnum{name=type, clazz=class net.minecraft.server.v1_14_R1.BlockPropertyChestType, values=[SINGLE, LEFT, RIGHT]} as it does not exist in Block{minecraft:barrel}
    at net.minecraft.server.v1_14_R1.BlockDataAbstract.get(BlockDataAbstract.java:93) ~[patched_1.14.3.jar:git-Paper-134]
    at com.lishid.openinv.internal.v1_14_R1.AnySilentContainer.isAnyContainerNeeded(AnySilentContainer.java:109) ~[?:?]
    at com.lishid.openinv.listeners.PlayerListener.onPlayerInteract(PlayerListener.java:65) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor544.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.3.jar:git-Paper-134]
    at org.bukkit.plugin.EventExecutor$$Lambda$2532.0000000001155DB0.execute(Unknown Source) ~[?:?]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.3.jar:git-Paper-134]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.3.jar:git-Paper-134]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.3.jar:git-Paper-134]
    at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:445) ~[patched_1.14.3.jar:git-Paper-134]
    at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:443) ~[patched_1.14.3.jar:git-Paper-134]
    at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1398) ~[patched_1.14.3.jar:git-Paper-134]
    at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.14.3.jar:git-Paper-134]
    at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.14.3.jar:git-Paper-134]
    at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.3.jar:git-Paper-134]
    at net.minecraft.server.v1_14_R1.PlayerConnectionUtils$$Lambda$3743.000000006807F7B0.run(Unknown Source) ~[?:?]
    at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.3.jar:git-Paper-134]
    at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.3.jar:git-Paper-134]
    at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.3.jar:git-Paper-134]
    at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.3.jar:git-Paper-134]
    at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[patched_1.14.3.jar:git-Paper-134]
    at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[patched_1.14.3.jar:git-Paper-134]
    at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[patched_1.14.3.jar:git-Paper-134]
    at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:978) ~[patched_1.14.3.jar:git-Paper-134]
    at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[patched_1.14.3.jar:git-Paper-134]
    at java.lang.Thread.run(Thread.java:819) [?:1.8.0_212]
```

**Comment by Jikoo** [comment]
Man, I'm getting careless, my bad. Fixed in 4.0.5 along with another mistake.
