### ISSUE TITLE
Not seeing anything in inventory

### ISSUE THREAD

**Issue by Ralph17** [lishid/OpenInv#173]
Im using paper 1.12.2 and if i try and open something i cant see anything in the inv even there are items in the players inventory also im getting this error 

[14:31:02 WARN]: [Essentials] XMPP is not configured properly. If you do not know what XMPP is, you may wish to remove the EssentialsXXMPP plugin from your server.
[14:31:05 INFO]: F4RostyFinn issued server command: /oi
[14:31:05 WARN]: java.lang.IllegalAccessException: Can not set final net.minecraft.server.v1_12_R1.NonNullList field net.minecraft.server.v1_12_R1.PlayerInventory.items to net.minecraft.server.v1_12_R1.NonNullList
[14:31:05 WARN]: at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
[14:31:05 WARN]: at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
[14:31:05 WARN]: at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:79)
[14:31:05 WARN]: at java.base/java.lang.reflect.Field.set(Field.java:780)
[14:31:05 WARN]: at com.lishid.openinv.internal.v1_12_R1.SpecialPlayerInventory.setItemArrays(SpecialPlayerInventory.java:165)
[14:31:05 WARN]: at com.lishid.openinv.internal.v1_12_R1.SpecialPlayerInventory.<init>(SpecialPlayerInventory.java:44)
[14:31:05 WARN]: at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14:31:05 WARN]: at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[14:31:05 WARN]: at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[14:31:05 WARN]: at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[14:31:05 WARN]: at com.lishid.openinv.util.InternalAccessor.createObject(InternalAccessor.java:103)
[14:31:05 WARN]: at com.lishid.openinv.util.InternalAccessor.newSpecialPlayerInventory(InternalAccessor.java:210)
[14:31:05 WARN]: at com.lishid.openinv.OpenInv.getSpecialInventory(OpenInv.java:327)
[14:31:05 WARN]: at com.lishid.openinv.commands.OpenInvPluginCommand.openInventory(OpenInvPluginCommand.java:148)
[14:31:05 WARN]: at com.lishid.openinv.commands.OpenInvPluginCommand.access$100(OpenInvPluginCommand.java:33)
[14:31:05 WARN]: at com.lishid.openinv.commands.OpenInvPluginCommand$1$1.run(OpenInvPluginCommand.java:89)
[14:31:05 WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[14:31:05 WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[14:31:05 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840)
[14:31:05 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[14:31:05 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[14:31:05 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[14:31:05 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by Jikoo** [comment]
Unfortunately, you will have to downgrade Java to use a version of OpenInv that supports 1.12 out of the box. 1.13 and up support Java 9+, 1.12 and lower require Java 8 or lower due to changes that were made to Java's reflection API.

I personally am not willing to work with server versions that outdated, but you could fork OpenInv, reset to the correct tag from back in 2019, and backport the changes in c5c1f471672ef1aa21c1beea986df885b085052a.

**Comment by Ralph17** [comment]
Where can i download that @Jikoo

**Comment by Ralph17** [comment]
i dont get it xd

**Comment by RoboMWM** [comment]
bukkitdev.

**Comment by Ralph17** [comment]
so your saying that my server needs to be higher then 1.12.2 or it wil simply just not work

**Comment by RoboMWM** [comment]
> so your saying that my server needs to be higher then 1.12.2 or it wil simply just not work

That's one of the options and is the easiest one. And recommended.

The other option is to downgrade java and use an older version of OpenInv.

**Comment by Ralph17** [comment]
But how do you downgrade java xd
thx for the help btw

**Comment by Jikoo** [comment]
Uninstalling then reinstalling the desired version should work.
