### ISSUE TITLE
Not working on newest version paper (#475,1.16.5)

### ISSUE THREAD

**Issue by steveq7** [lishid/OpenInv#179]
[08:27:22] [Server thread/WARN]: [OpenInv] Task #30872 for OpenInv v4.1.5 generated an exception
java.lang.AbstractMethodError: Receiver class com.lishid.openinv.internal.v1_16_R3.PlayerDataManager$2 does not define or inherit an implementation of the resolved method abstract title()Lnet/kyori/adventure/text/Component; of abstract class org.bukkit.inventory.InventoryView.
	at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftContainer.<init>(CraftContainer.java:54) ~[patched_1.16.5.jar:git-Paper-475]
	at com.lishid.openinv.internal.v1_16_R3.PlayerDataManager$3.<init>(PlayerDataManager.java:237) ~[?:?]
	at com.lishid.openinv.internal.v1_16_R3.PlayerDataManager.openInventory(PlayerDataManager.java:237) ~[?:?]
	at com.lishid.openinv.OpenInv.openInventory(OpenInv.java:265) ~[?:?]
	at com.lishid.openinv.commands.OpenInvCommand.openInventory(OpenInvCommand.java:173) ~[?:?]
	at com.lishid.openinv.commands.OpenInvCommand.access$100(OpenInvCommand.java:34) ~[?:?]
	at com.lishid.openinv.commands.OpenInvCommand$1$1.run(OpenInvCommand.java:92) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-475]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-475]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294) ~[patched_1.16.5.jar:git-Paper-475]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-475]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.5.jar:git-Paper-475]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.5.jar:git-Paper-475]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-475]
	at java.lang.Thread.run(Thread.java:834) [?:?] # #

**Comment by takatalvi** [comment]
Same issue on Paper build 478.

**Comment by Jikoo** [comment]
Downgrade to a version of Paper prior to them adding that method to InventoryView for now. Will look into it soon™️

**Comment by Jikoo** [comment]
Looks like Paper will be resolving this on their end (PaperMC/Paper#5222), which is a relief, because I'd either have to find some new hack or bundle Kyori to maintain compatibility with Spigot.
