### ISSUE TITLE
1.11 update

### ISSUE THREAD

**Issue by seema84** [lishid/OpenInv#51]
`
 Error occurred while enabling OpenInv v2.3.9 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_10_R1/World
	at com.lishid.openinv.OpenInv.onEnable(OpenInv.java:66) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.jar:git-Spigot-d60de0a-54450b7]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.jar:git-Spigot-d60de0a-54450b7]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.jar:git-Spigot-d60de0a-54450b7]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:373) [spigot-1.11.jar:git-Spigot-d60de0a-54450b7]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot-1.11.jar:git-Spigot-d60de0a-54450b7]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [spigot-1.11.jar:git-Spigot-d60de0a-54450b7]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [spigot-1.11.jar:git-Spigot-d60de0a-54450b7]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [spigot-1.11.jar:git-Spigot-d60de0a-54450b7]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.jar:git-Spigot-d60de0a-54450b7]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.jar:git-Spigot-d60de0a-54450b7]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_10_R1.World
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.11.jar:git-Spigot-d60de0a-54450b7]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.11.jar:git-Spigot-d60de0a-54450b7]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_102]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_102]
	... 12 more
`

**Comment by EvilOlaf** [comment]
Openinv using NMS and probably has not been updated to 1.11 yet

**Comment by seema84** [comment]
i know .. its an update note

**Comment by jjm223** [comment]
This plugin has been updated to 1.11.
