### ISSUE TITLE
java.lang.NoSuchFieldException

### ISSUE THREAD

**Issue by molor** [lishid/OpenInv#66]
Paper/Spigot 1.12, OpenInv 3.2.0, when I type /inv [online player]

```
[2017-06-09 17:26:34 | Server thread] java.lang.NoSuchFieldException: g
[2017-06-09 17:26:34 | Server thread] 	at java.lang.Class.getDeclaredField(Unknown Source)
[2017-06-09 17:26:34 | Server thread] 	at com.lishid.openinv.internal.v1_12_R1.SpecialPlayerInventory.setItemArrays(SpecialPlayerInventory.java:169)
[2017-06-09 17:26:34 | Server thread] 	at com.lishid.openinv.internal.v1_12_R1.SpecialPlayerInventory.<init>(SpecialPlayerInventory.java:38)
[2017-06-09 17:26:34 | Server thread] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2017-06-09 17:26:34 | Server thread] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[2017-06-09 17:26:34 | Server thread] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2017-06-09 17:26:34 | Server thread] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2017-06-09 17:26:34 | Server thread] 	at com.lishid.openinv.util.InternalAccessor.createObject(InternalAccessor.java:103)
[2017-06-09 17:26:34 | Server thread] 	at com.lishid.openinv.util.InternalAccessor.newSpecialPlayerInventory(InternalAccessor.java:212)
[2017-06-09 17:26:34 | Server thread] 	at com.lishid.openinv.OpenInv.getSpecialInventory(OpenInv.java:306)
[2017-06-09 17:26:34 | Server thread] 	at com.lishid.openinv.commands.OpenInvPluginCommand.openInventory(OpenInvPluginCommand.java:148)
[2017-06-09 17:26:34 | Server thread] 	at com.lishid.openinv.commands.OpenInvPluginCommand.access$100(OpenInvPluginCommand.java:33)
[2017-06-09 17:26:34 | Server thread] 	at com.lishid.openinv.commands.OpenInvPluginCommand$1$1.run(OpenInvPluginCommand.java:89)
[2017-06-09 17:26:34 | Server thread] 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
[2017-06-09 17:26:34 | Server thread] 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356)
[2017-06-09 17:26:34 | Server thread] 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:829)
[2017-06-09 17:26:34 | Server thread] 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:409)
[2017-06-09 17:26:34 | Server thread] 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:763)
[2017-06-09 17:26:34 | Server thread] 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:661)
[2017-06-09 17:26:34 | Server thread] 	at java.lang.Thread.run(Unknown Source)
```

**Comment by Jikoo** [comment]
Whoops. Will have this fixed shortly, I swear I double checked those field names.

**Comment by Jikoo** [comment]
[3.2.1](https://github.com/lishid/OpenInv/releases/tag/3.2.1)
