### ISSUE TITLE
concurrent modification exception

### ISSUE THREAD

**Issue by PhanaticD** [lishid/OpenInv#71]
```
[02:22:42] [Server thread/WARN]: java.util.ConcurrentModificationException
[02:22:42] [Server thread/WARN]:    at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1211)
[02:22:42] [Server thread/WARN]:    at java.util.TreeMap$EntryIterator.next(TreeMap.java:1247)
[02:22:42] [Server thread/WARN]:    at java.util.TreeMap$EntryIterator.next(TreeMap.java:1242)
[02:22:42] [Server thread/WARN]:    at com.google.common.collect.AbstractMapBasedMultimap$Itr.next(AbstractMapBasedMultimap.java:1177)
[02:22:42] [Server thread/WARN]:    at com.lishid.openinv.util.Cache.lazyCheck(Cache.java:149)
[02:22:42] [Server thread/WARN]:    at com.lishid.openinv.util.Cache.invalidate(Cache.java:105)
[02:22:42] [Server thread/WARN]:    at com.lishid.openinv.util.Cache.put(Cache.java:60)
[02:22:42] [Server thread/WARN]:    at com.lishid.openinv.OpenInv.getSpecialInventory(OpenInv.java:309)
[02:22:42] [Server thread/WARN]:    at com.lishid.openinv.commands.OpenInvPluginCommand.openInventory(OpenInvPluginCommand.java:148)
[02:22:42] [Server thread/WARN]:    at com.lishid.openinv.commands.OpenInvPluginCommand.access$100(OpenInvPluginCommand.java:33)
[02:22:42] [Server thread/WARN]:    at com.lishid.openinv.commands.OpenInvPluginCommand$1$1.run(OpenInvPluginCommand.java:89)
[02:22:42] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
[02:22:42] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356)
[02:22:42] [Server thread/WARN]:    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:832)
[02:22:42] [Server thread/WARN]:    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[02:22:42] [Server thread/WARN]:    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766)
[02:22:42] [Server thread/WARN]:    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664)
[02:22:42] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)

```

**Comment by Kakifrucht** [comment]
Openinv version?
#69

**Comment by PhanaticD** [comment]
3.3.0

**Comment by Jikoo** [comment]
I feel silly for not having noticed the real cause before, should be fixed now. Won't bother pushing a release yet because old Paper is apparently having issues, but in the meantime here's [OpenInv-recent 3.3.1-SNAPSHOT](https://github.com/lishid/OpenInv/files/1203412/OpenInv.zip).
