### ISSUE TITLE
Getting this issue

### ISSUE THREAD

**Issue by LogGits** [lishid/OpenInv#78]
Dont know what has caused it but im getting this error:
```
19:08:09org.bukkit.event.EventException: null
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1209]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1209]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1209]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [patched_1.12.2.jar:git-Paper-1209]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [patched_1.12.2.jar:git-Paper-1209]
at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:423) [patched_1.12.2.jar:git-Paper-1209]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1111) [patched_1.12.2.jar:git-Paper-1209]
at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:290) [patched_1.12.2.jar:git-Paper-1209]
at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:184) [patched_1.12.2.jar:git-Paper-1209]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:940) [patched_1.12.2.jar:git-Paper-1209]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) [patched_1.12.2.jar:git-Paper-1209]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1209]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1209]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.util.ConcurrentModificationException
at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1207) ~[?:1.8.0_91]
at java.util.TreeMap$EntryIterator.next(TreeMap.java:1243) ~[?:1.8.0_91]
at java.util.TreeMap$EntryIterator.next(TreeMap.java:1238) ~[?:1.8.0_91]
at com.google.common.collect.AbstractMapBasedMultimap$Itr.next(AbstractMapBasedMultimap.java:1177) ~[patched_1.12.2.jar:git-Paper-1209]
at com.lishid.openinv.util.Cache.lazyCheck(Cache.java:149) ~[OpenInv.jar:?]
at com.lishid.openinv.util.Cache.containsKey(Cache.java:91) ~[OpenInv.jar:?]
at com.lishid.openinv.OpenInv.setPlayerOffline(OpenInv.java:567) ~[OpenInv.jar:?]
at com.lishid.openinv.listeners.PlayerListener.onPlayerQuit(PlayerListener.java:48) ~[OpenInv.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor164.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1209]
... 13 more
```

**Comment by Jikoo** [comment]
Right, I'd fixed this but never actually pushed a release. [OpenInv 3.3.1-SNAPSHOT](https://github.com/lishid/OpenInv/files/1203412/OpenInv.zip) should work fine.

**Comment by Jikoo** [comment]
[3.3.1](https://github.com/lishid/OpenInv/releases/tag/3.3.1) officially released at long last.
