### ISSUE TITLE
crash events

### ISSUE THREAD

**Issue by Fargus5** [lishid/OpenInv#80]
[20:58:36] [Server thread/ERROR]: Could not pass event PlayerChangedWorldEvent to OpenInv v3.3.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.PlayerList.moveToWorld(PlayerList.java:707) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.teleport(CraftPlayer.java:509) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at com.earth2me.essentials.Teleport.now(Teleport.java:127) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.Teleport.teleport(Teleport.java:198) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.Teleport.back(Teleport.java:264) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.commands.Commandback.run(Commandback.java:25) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:157) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:511) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:424) [EssentialsX-2.0.1.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.util.ConcurrentModificationException
	at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1211) ~[?:1.8.0_111]
	at java.util.TreeMap$EntryIterator.next(TreeMap.java:1247) ~[?:1.8.0_111]
	at java.util.TreeMap$EntryIterator.next(TreeMap.java:1242) ~[?:1.8.0_111]
	at com.google.common.collect.AbstractMapBasedMultimap$Itr.next(AbstractMapBasedMultimap.java:1177) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at com.lishid.openinv.util.Cache.lazyCheck(Cache.java:149) ~[?:?]
	at com.lishid.openinv.util.Cache.containsKey(Cache.java:91) ~[?:?]
	at com.lishid.openinv.OpenInv.changeWorld(OpenInv.java:130) ~[?:?]
	at com.lishid.openinv.listeners.PlayerListener.onWorldChange(PlayerListener.java:53) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	... 28 more
[20:58:40] [Server thread/INFO]: Erenil issued server command: /vanish
[20:58:40] [Server thread/INFO]: [VanishNoPacket] Erenil reappeared.
[20:58:41] [Server thread/INFO]: Erenil issued server command: /vanish
[20:58:41] [Server thread/INFO]: [VanishNoPacket] Erenil disappeared.
[20:58:53] [Server thread/INFO]: Erenil issued server command: //paste -a
[20:58:58] [Server thread/INFO]: Erenil issued server command: //undo
[20:58:59] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_12_R1.ReportedException: Ticking entity
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:825) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at simplepets.brainsynder.nms.entities.v1_12_R1.EntityPet.getOwner(EntityPet.java:118) ~[?:?]
	at simplepets.brainsynder.pet.PetMoveEvent.<init>(PetMoveEvent.java:33) ~[?:?]
	at simplepets.brainsynder.nms.entities.v1_12_R1.EntityPet.move(EntityPet.java:408) ~[?:?]
	at net.minecraft.server.v1_12_R1.EntityLiving.a(EntityLiving.java:1805) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at simplepets.brainsynder.nms.entities.v1_12_R1.EntityPet.a(EntityPet.java:334) ~[?:?]
	at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2116) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.EntityInsentient.n(EntityInsentient.java:505) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1938) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:244) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1638) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1608) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1434) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:814) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	... 4 more
[20:58:59] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.NullPointerException: null
	at simplepets.brainsynder.nms.entities.v1_12_R1.EntityPet.getOwner(EntityPet.java:118) ~[?:?]
	at simplepets.brainsynder.pet.PetMoveEvent.<init>(PetMoveEvent.java:33) ~[?:?]
	at simplepets.brainsynder.nms.entities.v1_12_R1.EntityPet.move(EntityPet.java:408) ~[?:?]
	at net.minecraft.server.v1_12_R1.EntityLiving.a(EntityLiving.java:1805) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at simplepets.brainsynder.nms.entities.v1_12_R1.EntityPet.a(EntityPet.java:334) ~[?:?]
	at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2116) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.EntityInsentient.n(EntityInsentient.java:505) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1938) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:244) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1638) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1608) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1434) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:814) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(

**Comment by Jikoo** [comment]
This is OpenInv, not SimplePets.

**Comment by Fargus5** [comment]
Hi

The first line start speaking about openinv

ad/ERROR]: Could not pass event PlayerChangedWorldEvent to OpenInv v3.3.0

Anyway... could u explain to me what is CME? What kind of update did u give me? It's not a jar file...

**Comment by Jikoo** [comment]
>Caused by: java.util.ConcurrentModificationException

The file is a jar file, the extension was changed to .zip for the purposes of uploading in comments without a full release. Just rename it to OpenInv.jar

**Comment by Fargus5** [comment]
ok thanks
