### ISSUE TITLE
IllegalAccessException in Java 9+

### ISSUE THREAD

**Issue by Schneidertm** [lishid/OpenInv#93]
Hey - thank you so much for mainting this plugin <3. Here is a error I stumpling about recently. 
```
[22:54:19 WARN]: java.lang.IllegalAccessException: Can not set final net.minecraft.server.v1_13_R2.NonNullList field net.minecraft.server.v1_13_R2.PlayerInventory.items to net.minecraft.server.v1_13_R2.NonNullList
[22:54:19 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
[22:54:19 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
[22:54:19 WARN]:        at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:79)
[22:54:19 WARN]:        at java.base/java.lang.reflect.Field.set(Field.java:780)
[22:54:19 WARN]:        at com.lishid.openinv.internal.v1_13_R2.SpecialPlayerInventory.setItemArrays(SpecialPlayerInventory.java:161)
[22:54:19 WARN]:        at com.lishid.openinv.internal.v1_13_R2.SpecialPlayerInventory.<init>(SpecialPlayerInventory.java:43)
[22:54:19 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[22:54:19 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[22:54:19 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[22:54:19 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[22:54:19 WARN]:        at com.lishid.openinv.util.InternalAccessor.createObject(InternalAccessor.java:103)
[22:54:19 WARN]:        at com.lishid.openinv.util.InternalAccessor.newSpecialPlayerInventory(InternalAccessor.java:210)
[22:54:19 WARN]:        at com.lishid.openinv.OpenInv.getSpecialInventory(OpenInv.java:327)
[22:54:19 WARN]:        at com.lishid.openinv.commands.OpenInvPluginCommand.openInventory(OpenInvPluginCommand.java:148)
[22:54:19 WARN]:        at com.lishid.openinv.commands.OpenInvPluginCommand.access$100(OpenInvPluginCommand.java:33)
[22:54:19 WARN]:        at com.lishid.openinv.commands.OpenInvPluginCommand$1$1.run(OpenInvPluginCommand.java:89)
[22:54:19 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63)
[22:54:19 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[22:54:19 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008)
[22:54:19 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[22:54:19 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
[22:54:19 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)
[22:54:19 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by catb0t** [comment]
What were you doing before the exception?

**Comment by Schneidertm** [comment]
I'm tried to execute `/openinv <player>` or `/openender <player>`. However any empty inventory pops up along with the error in my server console.

**Comment by Jikoo** [comment]
Huh, what java version are you using? I've never seen `java.base/` prepended on stack trace lines.

I'll look into it, but I'm not sure what could be causing that - we [remove the final modifier](https://github.com/lishid/OpenInv/blob/master/internal/v1_13_R2/src/main/java/com/lishid/openinv/internal/v1_13_R2/SpecialPlayerInventory.java#L160) prior to setting. It's not a SecurityManager or anything like that, it'd be a different error. The modifier just appears to not be changed.

**Comment by Schneidertm** [comment]
I'm so sorry for being that bad at providing information. I assume my error is caused by my java version as I'm using `"11.0.1" 2018-10-16 LTS`

**Comment by RoboMWM** [comment]
Curious if this has anything to do with some of the reflection stuff being removed in post-version 8 java.

**Comment by Jikoo** [comment]
Yeah, I assume somewhere in Java 9 OpenInv broke. Not sure how to handle it, honestly. I really don't want to encourage people to stay on Java 8, but all the good alternatives I can come up with are massive changes I definitely don't have time to implement for a while.

I guess the easiest temp fix would be to just override every ISpecialPlayerInventory manipulation method and redirect the entire inventory contents to a different list/array which actually is the internal one. It'd be way messier and prone to accidental breakages than it is now (for updates, I basically copy+paste, then review method diffs) but it should allow us to limp along.

**Comment by Jikoo** [comment]
Do containers open silently at all? Looks like it should be broken as well.

**Comment by Schneidertm** [comment]
Not sure what all is defined as containers - but chests do open silently as they used to be.

**Comment by Jikoo** [comment]
Interesting, so reflection in Java 9+ still allows accessing private variables, but doesn't allow removing the final modifier. Could be worse I guess.

**Comment by TRose2000** [comment]
when will this be fixed. seems to be a little bit inactive ans people need this..

**Comment by Jikoo** [comment]
>when will this be fixed. seems to be a little bit inactive ans people need this..

I haven't had much free time lately, though I'll admit this isn't a high priority for me due to the low percentage of servers using anything other than Java 8.
I'll try to make a junky copy+paste workaround this week, but if anyone wants to take a stab at a higher quality solution that's certainly welcome.

**Comment by Jikoo** [comment]
Please try [OpenInv 3.3.8-SNAPSHOT](https://github.com/lishid/OpenInv/files/3075576/OpenInv.zip). Theoretically should work, but it's nowhere near as clean as it could be.

**Comment by Jikoo** [comment]
[4.0.0](https://github.com/lishid/OpenInv/releases/tag/4.0.0) fixes Java 9+ issues.
