### ISSUE TITLE
The server does not load the plugin

### ISSUE THREAD

**Issue by Uhevela** [lishid/OpenInv#96]
Hello,
My server does not load the plugin....
Here is the error 

[13:28:41][Server thread/ERROR]: Could not load 'plugins/OpenInv.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:161) ~[patched_1.13.2.jar:git-Paper-499]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136) ~[patched_1.13.2.jar:git-Paper-499]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:329) ~[patched_1.13.2.jar:git-Paper-499]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-499]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-499]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.util.zip.ZipException: zip file is empty
        at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_191]
        at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_191]
        at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_191]
        at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_191]
        at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:149) 
 ~[patched_1.13.2.jar:git-Paper-499]

        ... 5 more

**Comment by RoboMWM** [comment]
Full log? I'm guessing you did a plugman reload instead of a proper server restart.

**Comment by RoboMWM** [comment]
Where did you download from? Also was this a server reload or a server restart?

**Comment by Uhevela** [comment]
I downloaded the plugin from the buckit page (https://dev.bukkit.org/projects/openinv) and restarted the server completely. Is it the plugin.yml that is invalid?

**Comment by Jikoo** [comment]
Re-download, looks like your download messed up. `java.util.zip.ZipException: zip file is empty`
